device_name = "mySyncHost"

[sync]
    port = 8889
    upload_limit = 0
    download_limit = 0

[web-ui]
    listen = "0.0.0.0:8888"
    user = "user"
    # the password must be stored as a sha256 hash
    password = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
    root_directory = "/mnt/data/sync"