# [[users]]
#     name = "hab"
#     commands = [
#         "* * * * * touch /tmp/totu",
#         "* * * * * touch /tmp/tita"
#     ]

# [[users]]
#     name = "root"
#     commands = [
#         "* * * * * touch /tmp/rotu"
#     ]