[ampache]
plan_path = "ampache"

[libowfat]
plan_path = "libowfat"

[libtorrent]
plan_path = "libtorrent"

[opentracker]
plan_path = "opentracker"

[php-fpm]
plan_path = "php-fpm"

[phpmyadmin]
plan_path = "phpmyadmin"

[postfixadmin]
plan_path = "postfixadmin"

[resilio-sync]
plan_path = "resilio-sync"

[thttpd]
plan_path = "thttpd"

[zlib-static]
plan_path = "zlib-static"