[agendav]
plan_path = "agendav"

[ampache]
plan_path = "ampache"

[baikal]
plan_path = "baikal"

[boost]
plan_path = "boost"

[certbot]
plan_path = "certbot"

[deluge]
plan_path = "deluge"

[dovecot]
plan_path = "dovecot"

[h5ai]
plan_path = "h5ai"

[libowfat]
plan_path = "libowfat"

[libmilter]
plan_path = "libmilter"

[libtorrent]
plan_path = "libtorrent"

[opendkim]
plan_path = "opendkim"

[opentracker]
plan_path = "opentracker"

[php-fpm]
plan_path = "php-fpm"

[phpmyadmin]
plan_path = "phpmyadmin"

[postfix]
plan_path = "postfix"

[postfixadmin]
plan_path = "postfixadmin"

[rainloop]
plan_path = "rainloop"

[resilio-sync]
plan_path = "resilio-sync"

[reverse-proxy]
plan_path = "reverse-proxy"

[thttpd]
plan_path = "thttpd"

[umurmur]
plan_path = "umurmur"

[zlib-static]
plan_path = "zlib-static"