[bind]
  address = "127.0.0.1"
  port = 8080

[phpmyadmin]
  blowfish_secret = "932.gOLqeUvJ9pwOU2=d{j08i.K2cKQ."
  absolute_uri = ""

  [phpmyadmin.server]
  host = "127.0.0.1"
  port = 3306
  allow_no_password = true