[bind]
  address = "127.0.0.1"
  port = 8080

[postfixadmin]
  # to fill in this value, generate a salt and compute: "salt + ':' sha1( salt + ':' + password )"
  # defaults to "password"
  setup_password = "4077dd588ed82f733284be92f8c286b5:0f7771fb4ef2cbb8e39da4d5a0bd45d4d7880a95"
  default_language = "en"
  homepage_url = "https://postfixadmin.domain.tld"

  [postfixadmin.database]
  # type can be one of:
  # mysql = MySQL 3.23 and 4.0, 4.1 or 5
  # mysqli = MySQL 4.1+ or MariaDB
  # pgsql = PostgreSQL
  # sqlite = SQLite 3
  type = "mysqli"
  host = "localhost"
  user = "postfix"
  password = "postfixadmin"
  name = "postfix"

  [postfixadmin.admin]
  email = ""
  name = "Postmaster"

  [postfixadmin.smtp]
  server = "localhost"
  port = "25"

  [postfixadmin.default_aliases]
  abuse = "abuse@change-this-to-your.domain.tld"
  hostmaster = "hostmaster@change-this-to-your.domain.tld"
  postmaster = "postmaster@change-this-to-your.domain.tld"
  webmaster = "webmaster@change-this-to-your.domain.tld"